---
- name: be sure httpd is installed
  yum: pkg=httpd state=installed
  tags: httpd

- name: create document root
  file: dest=/var/www/wordpress state=directory owner=apache group=apache mode=0755

- name: be sure httpd is configured
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
  notify:
    - restart httpd
  tags: httpd

- name: remove httpd welcome.conf
  file: path=/etc/httpd/conf.d/welcome.conf state=absent
  notify:
    - restart httpd
  tags: httpd

- name: be sure httpd is running and enabled
  service: name=httpd state=started enabled=yes
  tags: httpd
